try {
    let a=0
    console.log(b)
    console.log("program run successfully");
}
catch(err)
{
    console.log("this is an error")
    console.log(p)
}
finally{
    //used for 
    //close the file
    //exit the loop
    //write to the log file
    console.log("i am here")
}